language: python

sudo: false

env:
    - HYPOTHESIS_PROFILE=ci

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

install: "pip install codecov hypothesis hypothesis-pytest pytest-cov"

script: py.test --cov=./

after_success:
    - codecov
